### ISSUE TITLE
Project should be renamed to SwiftModules (Github Pages)

### ISSUE THREAD

**Issue by regnerjr** [SwiftModules/SwiftModules-Web#1]
This will allow the gihtub pages magic to work, and the Organization webpage will be automatically hosted at swiftmodules.github.io. 

Documentation: [https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages](https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages)

**Comment by brennanMKE** [comment]
I have the site set up on AWS S3 with CloudFront so I can deploy the static pages there. I believe I will use Grunt and Harpjs to process the markdown files for the content which will then be pushed up to S3. People can then report issues and submit PRs to this repo to improve the content over time.

In addition to the static site I will use Twitter, Facebook and Medium to share the content to make it easier to share and reach more people. Those are already set up. I also have a Tumblr feed. I may use IFTTT to automate the distribution of the content.
